### ISSUE TITLE
elixir 1.2.2

### ISSUE THREAD

**Issue by matteosister** [msaraiva/docker-alpine#7]
First of all, thank you! 
We are running your images in production for some weeks now, and I also discovered alpine linux which is really great.

Are you planning to add the new [elixir 1.2.2](https://github.com/elixir-lang/elixir/releases/tag/v1.2.2)? I could work on a pull request if you want.

**Comment by msaraiva** [comment]
@matteosister, I plan to add it sometime this weekend, but feel free to work on a PR. Contributions are always welcome ;)

**Comment by matteosister** [comment]
right now i do not have time...if by monday nothing shows up I'll work on a pr, it's a promise! :smile:

**Comment by msaraiva** [comment]
Done.

**Comment by matteosister** [comment]
thank you!!!! :heart_eyes:
